// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBojGvAgNRdgAsbS3rjJoHIyFVBk0J9D8o',
    appId: '1:997471303965:web:345e6f5ba3de9c41bb49f4',
    messagingSenderId: '997471303965',
    projectId: 'project-59357',
    authDomain: 'project-59357.firebaseapp.com',
    storageBucket: 'project-59357.appspot.com',
    measurementId: 'G-QEKX6SCP4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH1ulq8BjyjgDRSzMTTJDfpZQstWojl1Y',
    appId: '1:997471303965:android:167101c3ab9ab6d6bb49f4',
    messagingSenderId: '997471303965',
    projectId: 'project-59357',
    storageBucket: 'project-59357.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO7jkdG9vTZDro4kuAvGIquxXHqZeOT_0',
    appId: '1:997471303965:ios:30c59de40bcfd0dbbb49f4',
    messagingSenderId: '997471303965',
    projectId: 'project-59357',
    storageBucket: 'project-59357.appspot.com',
    androidClientId: '997471303965-bjo9lvv8pkqq4pnbrhth2gmmatk81mth.apps.googleusercontent.com',
    iosClientId: '997471303965-m1muodc8c767fssi8i1tdb3ceqe4u73s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO7jkdG9vTZDro4kuAvGIquxXHqZeOT_0',
    appId: '1:997471303965:ios:30c59de40bcfd0dbbb49f4',
    messagingSenderId: '997471303965',
    projectId: 'project-59357',
    storageBucket: 'project-59357.appspot.com',
    androidClientId: '997471303965-bjo9lvv8pkqq4pnbrhth2gmmatk81mth.apps.googleusercontent.com',
    iosClientId: '997471303965-m1muodc8c767fssi8i1tdb3ceqe4u73s.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBojGvAgNRdgAsbS3rjJoHIyFVBk0J9D8o',
    appId: '1:997471303965:web:a2960091ccbe12bfbb49f4',
    messagingSenderId: '997471303965',
    projectId: 'project-59357',
    authDomain: 'project-59357.firebaseapp.com',
    storageBucket: 'project-59357.appspot.com',
    measurementId: 'G-50NWN858DF',
  );
}
